
abstract: All you need to start with Catalyst
author: Sebastian Riedel
distribution_type: module
generated_by: Module::Install version 0.54
license: perl
name: Task-Catalyst
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst: 5.64
version: 1.60
