name: Task-Catalyst
version: 0.01
abstract: All you need to start with Catalyst
author: Sebastian Riedel
license: perl
distribution_type: module
requires:
  Catalyst: 0
  Catalyst::Plugin::FormValidator: 0
  Catalyst::Plugin::FormValidator::Simple: 0
  Catalyst::Plugin::FillInForm: 0
  Catalyst::Plugin::Prototype: 0
  Catalyst::Plugin::Singleton: 0
  Catalyst::Plugin::DefaultEnd: 0
  Catalyst::Plugin::SubRequest: 0
  Catalyst::Plugin::Session: 0
  Catalyst::Plugin::Session::Store::File: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::State::URI: 0
  Catalyst::Model::DBIC: 0
  Catalyst::Model::DBIC::Plain: 0
  Catalyst::View::TT: 0
  DBD::SQLite: 0
  YAML: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.39
