name: Task-Catalyst
version: 1.30
abstract: All you need to start with Catalyst
author: Sebastian Riedel
license: perl
distribution_type: module
requires:
  Catalyst: 5.58
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.39
