--- 
abstract: All you need to start with Catalyst
author: The Catalyst Core Team - see http://catalyst.perl.org/
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Task-Catalyst
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst: 5.7007
  Catalyst::Devel: 1.02
version: 2.0000
